/*
This script takes the values from the JSON object generated by ble.js
and puts them in the elements of a page. This page is very basic. You might
want to do something more with it.

created 6 Aug 2018
by Tom Igoe
*/

function fillDisplay(thisMeter) {
  // Is the meter connected or not?
  document.getElementById('connected').innerHTML = 'Connected';
  // assemble the meter reading's value, units, and order of magnitude:
  document.getElementById('value').innerHTML = thisMeter.negativePolarity
    + thisMeter.value;
  document.getElementById('units').innerHTML =  thisMeter.magnitude
    + thisMeter.units;
  // IF measuring voltage or amperage, indicate AC/DC:
  if (thisMeter.units === 'V' || thisMeter.units === 'A') {
    document.getElementById('acDc').innerHTML = thisMeter.acDc;
  }
  // if measuring non-contact voltage, indicate that, and clear units:
  if (thisMeter.ncv) {
    document.getElementById('value').innerHTML = thisMeter.ncv;
    document.getElementById('units').innerHTML = '';
  }
  // is auto-ranging on?
  if (thisMeter.autoRange) {
    document.getElementById('autoRange').innerHTML = 'AutoRange';
  } else {
    document.getElementById('autoRange').innerHTML = '';
  }
  // is the hold button on?
  if (thisMeter.hold) {
    document.getElementById('hold').innerHTML = 'hold';
  } else {
    document.getElementById('hold').innerHTML = '';
  }
  // what setting are you on?
  document.getElementById('setting').innerHTML = thisMeter.setting;
}

// clear all the display elements except the connection status:
function clearDisplay(meter) {
  document.getElementById('connected').innerHTML = 'Disconnected';
  document.getElementById('value').innerHTML = '';
  document.getElementById('units').innerHTML =  '';
  document.getElementById('acDc').innerHTML = '';
  document.getElementById('autoRange').innerHTML = '';
  document.getElementById('hold').innerHTML = '';
  document.getElementById('setting').innerHTML = '';
}
